[package]
name = "hof-blaze"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
hof-common = { path = "../hof-common" }
image = { version = "0.25", default-features = false, features = ["png"] }
tray-icon = "0.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
ctrlc = "3.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serialport = "4"
notify-rust = "4"
open = "5"
tokio = { version = "1", features = [
    "sync",
    "time",
    "macros",
    "rt-multi-thread",
] }
rfd = { version = "0.17.2", default-features = false, features = ["gtk3"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
libappindicator = { version = "0.9", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
winit = "0.30"

[target.'cfg(target_os = "macos")'.dependencies]
winit = "0.30"
